---
Author: "Youjin Zhang
title: "HW4"
output: html_document
---
#1 Create	the	vectors
#a) (1,2,3,...,19,20)
#b) (20,19,...,2,1)
#c) (1,2,3,...,19,20,19,18,...,2,1)	
#d) (4,	6,	3)	and	assign	it	to	the	name	tmp.	
#For	parts	(e),	(f)	and	(g)	look	at	the	help	for	the	function	rep.	
#e) (4,6,3,	4,6,3,...,4,6,3)	where	there	are	10	occurrences	of	4.	
#f) (4,6,3,	4,6,3,...,4,6,3,4)	where	there	are	11	occurrences	of	4,	10 occurrences	of	6	and	10	occurrences	of	3.	
#g) (4,4,...,4,	6,6,...,6,	3,3,...,3)	where	there	are	10	occurrences	of	4,	20	
#occurrences	of	6	and	30	occurrences	of	3.	
```{R 1a}
#a
(1:20)
```

```{R 1b}
#b
(20:1)
```

```{R 1c}
#c
c(1:20,19:1)
#c for combination
```

```{R 1d}
#d
#assign the vector to tmp
tmp <- c(4,6,3)
```

#using repitition functions
```{R 1e}
#e
rep(c(4,6,3), 10)
```

```{R 1f}
#f 
rep(c(4,6,3), len=31)
#total lenth equals 31
```

```{R 1g}
#g
rep(c(4,6,3), c(10,20,30))
```

#2 Create	a	vector	of	the	values	of	(e^x)cos(x)	at	x	=	3,3.1,3.2,...,5.9,6.
```{R 2}
#using in-buit sequence function
x <- seq(3,6,0.1)
exp(x)*cos(x)
#use exp(x) to express "e"
```

#3
```{R 3a}
#a
x <- 0.1^seq(3,36,by=3)
y <- 0.2^seq(1,34,by=3)
x*y
```

```{R 3b}
#b
c <- (1:25)
2^c/c
```

#4
```{R 4a}
#a
i <- (10:100)
y <- i^3+4i^2
sum(y)
```

```{R 4b}
#b
i <- (1:25)
y <- 2^i/i+3^i/i^2
sum(y)
```

#5 Use	the	function	paste	to	create	the	following	character	vectors	of	length	30:
#a) ("label	1",	"label	2",	.....,	"label	30"). Note	that	there	is	a	single	space	 between	label	and	the	number	following.
#b) ("fn1",	"fn2",	...,	"fn30").	In	this	case,	there	is	no	space	between	fn and	the	number	following.
```{R 5a}
#a
paste("label",1:30)
```

```{R 5b}
#b
paste("fn",1:30,sep="")
```

#6 Execute	the	following	lines	which	create	two	vectors	of	random	integers which	are	chosen	with	replacement	from	the	integers	0,	1,	.	.	.	,	999.	Both	vectors	have	length	250.
```{R 6}
xVec <- sample(0:999, 250, replace=T)
yVec <- sample(0:999, 250, replace=T)
#(a) 
yVec[-1] - xVec[-length(xVec)]
#(b) 
sin(yVec[-length(yVec)]) / cos(xVec[-1])
#(c) 
xVec[-c(249,250)] + 2*xVec[-c(1,250)]-xVec[-c(1,2)]
#or, for an answer which works whatever the length of xVec,
xVecLen <- length(xVec)
xVec[-c(xVecLen-1,xVecLen)] + 2*xVec[-c(1,xVecLen)] - xVec[-c(1,2)]
#(d) 
sum(exp(-xVec[-1])/(xVec[-length(xVec)]+10))
```

#7
```{R 7}
xVec <- sample(0:999, 250, replace=T)
yVec <- sample(0:999, 250, replace=T)
#(a) 
yVec[yVec>600]
#(b) 
(1:length(yVec))[yVec>600] #or which
(yVec>600)
#(c) 
xVec[yVec>600]
#(d) 
sqrt(abs(xVec-mean(xVec)))
#(e) 
sum( yVec>max(yVec)-200 )
#(f) 
sum(xVec%%2==0)
#(g) 
xVec[order(yVec)]
#(h) 
yVec[c(T,F,F)]
```

#8
```{R 8}
1+sum(cumprod(seq(2,38,b=2)/seq(3,39,b=2)))
```

