---
title: "gglot"
author: "Youjin Zhang"
date: "October 13, 2016"
output: html_document
---

library("ggplot2")
library("grid")
```{r}
#question1 histogram for columns
lapply(diamonds,class)#determine the type of each column
str(diamonds)
column_num <- diamonds[sapply(diamonds, is.numeric)]#find numeric columns
column_num=as.data.frame(column_num)
hist(column_num$carat)
for (i in 1:dim(column_num)[2]) {
hist(column_num[,i])}
column_num+geom_histogram(binwidth = 0.2) 
}
```

```{r}
#question2 Create	a	simple	scatter	plot	of	Weight (“Carat”) and	Price using	Color	(the	“Color” column	in	the	diamonds	dataframe)	as	a	facet. 

ggplot(diamonds,aes(x=carat,y=price,colour=factor(color)))+
  geom_point()+
       xlab("weight")+
       ylab("price")+
  ggtitle("Diamonds-Weight to Price by Color")
    
```

```{r}
#quetsion3
#nonlinear regression
ggplot(diamonds,aes(x=log(carat),y=log(price),colour=factor(color)))+
  geom_point()+
       xlab("weight")+
       ylab("price")+
  ggtitle("Weight to Price (Linear)")
```

```{r}
#question4
#residuals
diamonds_lm <- lm(log(price)~log(carat),diamonds)
ggplot(diamonds,aes(x=log(carat),y=resid(diamonds_lm),colour=factor(color)))+
  geom_point()+
       xlab("weight")+
       ylab("price residuals")+
  ggtitle("Weight to Price by Color")

```

```{r}
#question5
#draw density	histogram	of	the	price


```

